select * from customer
--Total revenue Generated by male vs. female customers ?

Select gender,sum(purchase_amount) as revenue
from customer
Group By gender

-- Which customer used a discount but still spent more than the average purchase amount

Select customer_id, purchase_amount
from customer 
where discount_applied = 'Yes' and purchase_amount >= (Select avg(purchase_amount) from customer)

-- Which are the top 5 products with higest average review rating

select item_purchased, avg(review_rating) as Average_rating
from customer
Group By item_purchased
Order By Average_rating DESC
Limit 5

-- Compare the average purchase amount between standard and express shipping
select shipping_type, Round(avg(purchase_amount),2) as avg_purchase
from customer
Where shipping_type in ('Standard','Express')
Group By shipping_type

-- Do subscrived customers spend more ? compare average
-- spend and total revenue between subscrivers and non-subscrivers

Select subscription_status, sum(purchase_amount) as revenue, avg(purchase_amount) as avg_spend,
count(customer_id) customer_count
from customer
where subscription_status in ('Yes','No')
Group By subscription_status
order By revenue,avg_spend DESC

--Which 5 products have the highest percentage of purchase 
--with discount applied

select item_purchased,
100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*) as discount_rate
from customer
group by item_purchased
order by discount_rate DESC
limit 5

--Segment customers into new,returning and loyal based on
--their total number of previous purchases and show the count
--of each segment

with customer_type as (

    select customer_id,previous_purchases,
	CASE 
	    When previous_purchases = 1 Then 'New'
		When previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
		END AS customer_segment
From customer
)

Select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

-- What are the top 3 most purchased Item withing each category

With item_count as (

   Select Category, item_purchased, COUNT(customer_id) as Total_orders,
   Row_Number() Over (partition By category Order By count(customer_id) DESC)
   as item_rank
   From customer
   Group By category,item_purchased
   
)

Select item_rank, category, item_purchased, Total_orders
From item_count
Where item_rank <= 3

--Are customers who are repeat buyers (More Than 5 previous purchases) also likely to subscrive

Select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
Group By subscription_status

--What is the revenue contribution of each age group

Select age_group,
SUM(purchase_amount) as total_revenue
From customer
Group By age_group
Order By total_revenue desc